### ISSUE TITLE
Remove access token from GitHub?

### ISSUE THREAD

**Issue by sjthatc1** [Chippd/erinValentine#1]
https://github.com/Chippd/erinValentine/blob/5eb3b34e49a78bd11477ddd5e2a95ca61d8628e9/scripts.js#L227

OP I'm too lazy to check but is this a valid access token?

**Comment by Chippd** [comment]
Hey, thanks for the heads up but this key was disabled. Bad practice for me to have it in there though yes, will probably move it to my own server or heroku and use ENV variables 👍
